"use client";

import {
  LayoutDashboard,
  BookOpen,
  Users,
  CalendarDays,
  BarChart3,
  Settings,
  LifeBuoy,
  LogOut,
  GraduationCap,
  CreditCard,
  Video,
  MessagesSquare,
  ClipboardList,
  Award,
  FileText,
  Wallet,
  Bell,
  Search,
  Plus,
  MoreVertical,
  PlayCircle,
  ChevronLeft,
  ChevronRight,
  Download,
  Upload,
  Filter,
  TrendingUp,
  CheckCircle,
  Timer,
  Building2,
  Shield,
  UserCog,
  Sparkles,
  Menu,
  X,
  ChevronDown,
  Pencil,
  Trash2,
  ExternalLink,
  Eye,
  EyeOff,
  Lock,
  Mail,
  Phone,
  MapPin,
  Star,
  Clock,
  Check,
  AlertTriangle,
  Info,
  Home,
  ListChecks,
  FileSpreadsheet,
  Presentation,
  HelpCircle,
  ArrowLeft,
  ArrowRight,
  Send,
  Paperclip,
  Image,
  CalendarCheck,
  UserCheck,
  DollarSign,
  BadgePercent,
  Receipt,
  Landmark,
  CloudUpload,
  Hourglass,
  Save,
  History,
  FolderArchive,
  Copy,
  BellOff,
  Pause,
  Play,
  StopCircle,
  User,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";
const iconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  menu_book: BookOpen,
  group: Users,
  calendar_today: CalendarDays,
  bar_chart: BarChart3,
  settings: Settings,
  help_outline: LifeBuoy,
  logout: LogOut,
  school: GraduationCap,
  payments: CreditCard,
  video: Video,
  forum: MessagesSquare,
  assignment: ClipboardList,
  award: Award,
  description: FileText,
  wallet: Wallet,
  notifications: Bell,
  search: Search,
  add: Plus,
  more_vert: MoreVertical,
  play_circle: PlayCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  download: Download,
  upload: Upload,
  filter_list: Filter,
  trending_up: TrendingUp,
  check_circle: CheckCircle,
  timer: Timer,
  domain: Building2,
  shield: Shield,
  admin_panel_settings: UserCog,
  sparkles: Sparkles,
  menu: Menu,
  close: X,
  expand_more: ChevronDown,
  edit: Pencil,
  delete: Trash2,
  open_in_new: ExternalLink,
  visibility: Eye,
  visibility_off: EyeOff,
  lock: Lock,
  mail: Mail,
  call: Phone,
  location_on: MapPin,
  star: Star,
  schedule: Clock,
  check: Check,
  warning: AlertTriangle,
  info: Info,
  home: Home,
  list_alt: ListChecks,
  spreadsheet: FileSpreadsheet,
  slideshow: Presentation,
  help: HelpCircle,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  send: Send,
  attach_file: Paperclip,
  image: Image,
  calendar_check: CalendarCheck,
  verified_user: UserCheck,
  currency_rupee: DollarSign,
  percent: BadgePercent,
  receipt_long: Receipt,
  account_balance: Landmark,
  cloud_upload: CloudUpload,
  hourglass_top: Hourglass,
  videocam: Video,
  save: Save,
  history_edu: History,
  folder_zip: FolderArchive,
  content_copy: Copy,
  notifications_off: BellOff,
  pause: Pause,
  play_arrow: Play,
  stop_circle: StopCircle,
  person: User,
  groups: Users,
};

export function Icon({
  name,
  className,
  style,
}: {
  name: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Cmp = iconMap[name] ?? Info;
  return <Cmp className={cn("h-5 w-5", className)} style={style} aria-hidden="true" />;
}
