import type { Role } from "@/lib/types";

export const currentUser = {
  id: "usr_001",
  name: "Arif Hussain",
  email: "arif.hussain@sunriseacademy.edu",
  role: "INSTITUTE_ADMIN" as Role,
  instituteId: "inst_001",
  instituteName: "Sunrise Academy",
  avatar: null,
};

export const mockInstitute = {
  id: "inst_001",
  name: "Sunrise Academy",
  slug: "sunrise",
  plan: "Professional",
  logo: null,
  banner: null,
  primaryColor: "#6366f1",
  secondaryColor: "#18181b",
  email: "admin@sunriseacademy.edu",
  phone: "+1 (555) 012-3456",
  address: "221 Innovation Drive, San Francisco, CA",
  website: "https://sunriseacademy.in",
  studentsCount: 2842,
  teachersCount: 96,
  coursesCount: 24,
  batchCount: 48,
  createdAt: "2023-01-15T00:00:00.000Z",
};

export const dashboardStats = {
  revenue: { total: 128400, growth: 12, currency: "USD" },
  activeStudents: { total: 2842, growth: 12 },
  todayClasses: { total: 18 },
  pendingAssignments: { total: 94 },
  teacherAttendance: { total: 94.8 },
  studentAttendance: { total: 92.4 },
  pendingFees: { total: 42105 },
  netGrowth: { total: 128400 },
  avgTuition: { total: 12500 },
};

export const revenueSeries = [
  { month: "JAN", revenue: 18400, enrollments: 142 },
  { month: "FEB", revenue: 21400, enrollments: 168 },
  { month: "MAR", revenue: 19800, enrollments: 151 },
  { month: "APR", revenue: 25600, enrollments: 201 },
  { month: "MAY", revenue: 22800, enrollments: 180 },
  { month: "JUN", revenue: 20400, enrollments: 159 },
];

export const announcements = [
  {
    id: "ann_1",
    type: "Urgent",
    title: "System Maintenance",
    description: "Portal will be down for scheduled maintenance tonight at 11:00 PM EST...",
    time: "2h ago",
    audience: "Institute",
  },
  {
    id: "ann_2",
    type: "Event",
    title: "Science Fair 2024",
    description: "Registration for the annual Inter-Institute Science Fair is now open for all...",
    time: "Yesterday",
    audience: "Batch",
  },
  {
    id: "ann_3",
    type: "Update",
    title: "Curriculum Change",
    description: "The Computer Science department has released updated course modules...",
    time: "May 12",
    audience: "Course",
  },
];

export const recentAdmissions = [
  {
    id: "AX-2024-089",
    name: "Ayesha Khan",
    initials: "AK",
    department: "Data Science",
    date: "May 14, 2024",
    status: "Verified",
    fees: "Paid",
  },
  {
    id: "AX-2024-090",
    name: "Rohan Sharma",
    initials: "RS",
    department: "Cybersecurity",
    date: "May 13, 2024",
    status: "Processing",
    fees: "Pending",
  },
  {
    id: "AX-2024-091",
    name: "Priya Patel",
    initials: "PP",
    department: "UX Design",
    date: "May 12, 2024",
    status: "Verified",
    fees: "Paid",
  },
  {
    id: "AX-2024-092",
    name: "Mohammed Imran",
    initials: "MI",
    department: "Cloud Engineering",
    date: "May 11, 2024",
    status: "Verified",
    fees: "Paid",
  },
  {
    id: "AX-2024-093",
    name: "Aisha Siddiqui",
    initials: "AS",
    department: "AI & ML",
    date: "May 10, 2024",
    status: "Processing",
    fees: "Pending",
  },
];

export const courses = [
  {
    id: "crs_001",
    code: "CS-402",
    title: "Advanced Distributed Systems",
    track: "Engineering Track",
    status: "Published",
    enrolled: 1240,
    rating: 4.9,
    reviews: 210,
    thumbnail: null,
    instructor: "Dr. Ayesha Ansari",
    modules: 8,
    lessons: 42,
  },
  {
    id: "crs_002",
    code: "AI-101",
    title: "Foundations of Neural Networks",
    track: "Intelligence Track",
    status: "Draft",
    enrolled: 0,
    rating: 0,
    reviews: 0,
    thumbnail: null,
    instructor: "Prof. Arjun Nair",
    modules: 5,
    lessons: 26,
  },
  {
    id: "crs_003",
    code: "DEV-098",
    title: "Mastering the Modern Toolchain",
    track: "Productivity Track",
    status: "Published",
    enrolled: 8450,
    rating: 5.0,
    reviews: 1200,
    thumbnail: null,
    instructor: "Dr. Kavya Reddy",
    modules: 6,
    lessons: 34,
  },
  {
    id: "crs_004",
    code: "DS-210",
    title: "Data Visualization with D3",
    track: "Data Track",
    status: "Published",
    enrolled: 980,
    rating: 4.8,
    reviews: 96,
    thumbnail: null,
    instructor: "Dr. Ayesha Ansari",
    modules: 4,
    lessons: 22,
  },
];

export const courseHealth = [
  { label: "Completion Rate", value: 76, icon: "play_circle" },
  { label: "Forum Activity", value: 42, icon: "forum" },
  { label: "Grading Queue", value: 90, icon: "assignment", danger: true, pending: 94 },
];

export const batches = [
  {
    id: "bat_001",
    name: "Advanced AI - Night Shift",
    code: "AI-N1",
    course: "Foundations of Neural Networks",
    teacher: "Prof. Arjun Nair",
    schedule: "Mon, Wed, Fri • 7:00 PM",
    students: 32,
    capacity: 40,
    status: "Active",
    startDate: "2024-04-01",
  },
  {
    id: "bat_002",
    name: "Distributed Systems - Morning",
    code: "DS-M1",
    course: "Advanced Distributed Systems",
    teacher: "Dr. Ayesha Ansari",
    schedule: "Tue, Thu • 9:00 AM",
    students: 28,
    capacity: 35,
    status: "Active",
    startDate: "2024-03-15",
  },
  {
    id: "bat_003",
    name: "Web Dev Bootcamp - Weekend",
    code: "WEB-W1",
    course: "Mastering the Modern Toolchain",
    teacher: "Dr. Kavya Reddy",
    schedule: "Sat, Sun • 11:00 AM",
    students: 40,
    capacity: 40,
    status: "Full",
    startDate: "2024-05-01",
  },
  {
    id: "bat_004",
    name: "Data Science - Evening",
    code: "DS-E2",
    course: "Data Visualization with D3",
    teacher: "Dr. Ayesha Ansari",
    schedule: "Mon, Thu • 6:00 PM",
    students: 18,
    capacity: 30,
    status: "Active",
    startDate: "2024-06-10",
  },
  {
    id: "bat_005",
    name: "AI Fast-Track - Summer",
    code: "AI-F1",
    course: "Foundations of Neural Networks",
    teacher: "Prof. Arjun Nair",
    schedule: "Daily • 10:00 AM",
    students: 24,
    capacity: 50,
    status: "Upcoming",
    startDate: "2024-07-01",
  },
];

export const students = [
  {
    id: "std_001",
    studentId: "AX-2023-001",
    name: "Ayesha Khan",
    initials: "AK",
    email: "ayesha.k@example.com",
    phone: "+1 555 0101",
    course: "Data Science",
    batch: "DS-E2",
    attendance: 96,
    status: "Active",
    enrolledOn: "May 14, 2024",
  },
  {
    id: "std_002",
    studentId: "AX-2023-002",
    name: "Rohan Sharma",
    initials: "RS",
    email: "rohan.s@example.com",
    phone: "+1 555 0102",
    course: "Cybersecurity",
    batch: "CS-N1",
    attendance: 88,
    status: "Active",
    enrolledOn: "May 13, 2024",
  },
  {
    id: "std_003",
    studentId: "AX-2023-003",
    name: "Priya Patel",
    initials: "PP",
    email: "priya.p@example.com",
    phone: "+1 555 0103",
    course: "UX Design",
    batch: "UX-M1",
    attendance: 92,
    status: "Active",
    enrolledOn: "May 12, 2024",
  },
  {
    id: "std_004",
    studentId: "AX-2023-004",
    name: "Mohammed Imran",
    initials: "MI",
    email: "mohammed.i@example.com",
    phone: "+1 555 0104",
    course: "Cloud Engineering",
    batch: "CL-M1",
    attendance: 74,
    status: "At Risk",
    enrolledOn: "May 11, 2024",
  },
  {
    id: "std_005",
    studentId: "AX-2023-005",
    name: "Aisha Siddiqui",
    initials: "AS",
    email: "aisha.s@example.com",
    phone: "+1 555 0105",
    course: "AI & ML",
    batch: "AI-N1",
    attendance: 99,
    status: "Active",
    enrolledOn: "May 10, 2024",
  },
];

export const teachers = [
  {
    id: "tch_001",
    name: "Dr. Ayesha Ansari",
    initials: "AA",
    email: "ayesha.ansari@sunriseacademy.edu",
    phone: "+1 555 0201",
    subjects: ["Data Science", "Distributed Systems"],
    batches: 4,
    students: 220,
    attendance: 97,
    status: "Active",
  },
  {
    id: "tch_002",
    name: "Prof. Arjun Nair",
    initials: "AN",
    email: "arjun.nair@sunriseacademy.edu",
    phone: "+1 555 0202",
    subjects: ["AI & ML", "Neural Networks"],
    batches: 3,
    students: 180,
    attendance: 94,
    status: "Active",
  },
  {
    id: "tch_003",
    name: "Dr. Kavya Reddy",
    initials: "KR",
    email: "kavya.reddy@sunriseacademy.edu",
    phone: "+1 555 0203",
    subjects: ["Web Development", "Tooling"],
    batches: 5,
    students: 310,
    attendance: 91,
    status: "On Leave",
  },
  {
    id: "tch_004",
    name: "Vikram Singh",
    initials: "VS",
    email: "vikram.singh@sunriseacademy.edu",
    phone: "+1 555 0204",
    subjects: ["Cybersecurity"],
    batches: 2,
    students: 120,
    attendance: 89,
    status: "Active",
  },
];

export const liveClasses = [
  {
    id: "live_001",
    title: "Introduction to UI Design Systems",
    course: "Mastering the Modern Toolchain",
    batch: "WEB-W1",
    teacher: "Dr. Kavya Reddy",
    roomId: "room_xyz123",
    status: "Live",
    startsIn: "14m",
    location: "Main Lecture Hall A2",
    registered: 28,
    startTime: "2024-06-15T14:00:00Z",
  },
  {
    id: "live_002",
    title: "Recurrence Relations & Master Theorem",
    course: "Advanced Distributed Systems",
    batch: "DS-M1",
    teacher: "Dr. Ayesha Ansari",
    roomId: "room_abc456",
    status: "Scheduled",
    startsIn: "2h 20m",
    location: "Lecture Hall B1",
    registered: 31,
    startTime: "2024-06-15T16:30:00Z",
  },
  {
    id: "live_003",
    title: "Backpropagation Deep Dive",
    course: "Foundations of Neural Networks",
    batch: "AI-N1",
    teacher: "Prof. Arjun Nair",
    roomId: "room_def789",
    status: "Scheduled",
    startsIn: "Tomorrow 7:00 PM",
    location: "Online • AI-N1 Room",
    registered: 32,
    startTime: "2024-06-16T19:00:00Z",
  },
  {
    id: "live_004",
    title: "D3 Scales & Axes Workshop",
    course: "Data Visualization with D3",
    batch: "DS-E2",
    teacher: "Dr. Ayesha Ansari",
    roomId: "room_ghi101",
    status: "Ended",
    startsIn: "Completed",
    location: "Lab 3",
    registered: 18,
    startTime: "2024-06-14T18:00:00Z",
    recordingUrl: "https://example.com/recording/ghi101",
  },
];

export const recordedLectures = [
  {
    id: "rec_001",
    title: "The History of Distributed Tech",
    course: "Advanced Distributed Systems",
    module: "Module 1: Introduction to Latency",
    duration: "12:04",
    size: "1.2 GB",
    uploadedBy: "Dr. Ayesha Ansari",
    uploadedAt: "2 hours ago",
    visibility: "Batch Only",
    thumbnail: null,
  },
  {
    id: "rec_002",
    title: "React Fundamentals Workshop",
    course: "Mastering the Modern Toolchain",
    module: "Module 2: Component Architecture",
    duration: "48:20",
    size: "1.8 GB",
    uploadedBy: "Dr. Kavya Reddy",
    uploadedAt: "Yesterday",
    visibility: "Course Wide",
    thumbnail: null,
  },
  {
    id: "rec_003",
    title: "Gradient Descent Explained",
    course: "Foundations of Neural Networks",
    module: "Module 1: Core Concepts",
    duration: "24:45",
    size: "860 MB",
    uploadedBy: "Prof. Arjun Nair",
    uploadedAt: "3 days ago",
    visibility: "Public",
    thumbnail: null,
  },
  {
    id: "rec_004",
    title: "CAP Theorem Principles (Reading)",
    course: "Advanced Distributed Systems",
    module: "Module 1: Introduction to Latency",
    duration: "PDF • 12.4 MB",
    size: "12.4 MB",
    uploadedBy: "Dr. Ayesha Ansari",
    uploadedAt: "3 days ago",
    visibility: "Batch Only",
    thumbnail: null,
  },
];

export const payments = [
  {
    id: "pay_001",
    txId: "TXN-2024-0901",
    student: "Ayesha Khan",
    studentId: "AX-2023-001",
    course: "Data Science Pro",
    amount: 499,
    method: "Razorpay",
    status: "Success",
    date: "Jun 14, 2024",
    invoice: "INV-2024-011",
  },
  {
    id: "pay_002",
    txId: "TXN-2024-0902",
    student: "Rohan Sharma",
    studentId: "AX-2023-002",
    course: "Cybersecurity Bootcamp",
    amount: 899,
    method: "Card",
    status: "Success",
    date: "Jun 13, 2024",
    invoice: "INV-2024-012",
  },
  {
    id: "pay_003",
    txId: "TXN-2024-0903",
    student: "Priya Patel",
    studentId: "AX-2023-003",
    course: "UX Design Mastery",
    amount: 650,
    method: "Razorpay",
    status: "Pending",
    date: "Jun 13, 2024",
    invoice: "INV-2024-013",
  },
  {
    id: "pay_004",
    txId: "TXN-2024-0904",
    student: "Mohammed Imran",
    studentId: "AX-2023-004",
    course: "Cloud Engineering",
    amount: 750,
    method: "UPI",
    status: "Refunded",
    date: "Jun 12, 2024",
    invoice: "INV-2024-014",
  },
];

export const messages = [
  {
    id: "msg_001",
    name: "Sunita Verma",
    role: "Student",
    preview: "Ma'am, I've attached my assignment draft...",
    time: "2m",
    unread: 2,
    online: true,
    initials: "SV",
  },
  {
    id: "msg_002",
    name: "Prof. Arjun Nair",
    role: "Faculty",
    preview: "The batch schedule for next week is confirmed...",
    time: "1h",
    unread: 0,
    online: true,
    initials: "AN",
  },
  {
    id: "msg_003",
    name: "Ayesha Khan",
    role: "Student",
    preview: "Thanks for the feedback on my quiz!",
    time: "3h",
    unread: 1,
    online: false,
    initials: "AK",
  },
  {
    id: "msg_004",
    name: "IT Helpdesk",
    role: "Support",
    preview: "Your ticket #4821 has been resolved.",
    time: "1d",
    unread: 0,
    online: false,
    initials: "IT",
  },
];

export const chatThread = [
  {
    id: "c1",
    from: "Sunita Verma",
    mine: false,
    text: "Ma'am, I've attached my assignment draft for the distributed systems project.",
    time: "10:42 AM",
  },
  {
    id: "c2",
    from: "Me",
    mine: true,
    text: "Got it Sunita. I'll review the CAP theorem section and leave inline comments.",
    time: "10:45 AM",
  },
  {
    id: "c3",
    from: "Sunita Verma",
    mine: false,
    text: "Thank you! Also should I include the latency benchmarks from the lab?",
    time: "10:47 AM",
  },
  {
    id: "c4",
    from: "Me",
    mine: true,
    text: "Yes, add them as an appendix. Great work so far.",
    time: "10:49 AM",
  },
];

export const notifications = [
  {
    id: "not_001",
    type: "Assignment",
    title: "New submission from Ayesha Khan",
    time: "5m ago",
    read: false,
  },
  {
    id: "not_002",
    type: "Payment",
    title: "Payment of $499 received from Rohan Sharma",
    time: "1h ago",
    read: false,
  },
  {
    id: "not_003",
    type: "Attendance",
    title: "3 students marked absent in DS-M1",
    time: "3h ago",
    read: false,
  },
  {
    id: "not_004",
    type: "System",
    title: "Weekly report is ready to download",
    time: "Yesterday",
    read: true,
  },
];

export const activity = [
  {
    id: "act_001",
    actor: "Dr. Ayesha Ansari",
    action: "created course",
    target: "Advanced Distributed Systems",
    time: "2m ago",
    type: "course",
  },
  {
    id: "act_002",
    actor: "System",
    action: "enrolled student",
    target: "Ayesha Khan → Data Science Pro",
    time: "14m ago",
    type: "student",
  },
  {
    id: "act_003",
    actor: "Dr. Kavya Reddy",
    action: "uploaded lecture",
    target: "React Fundamentals Workshop",
    time: "1h ago",
    type: "lecture",
  },
  {
    id: "act_004",
    actor: "Payments",
    action: "received payment",
    target: "$499 from Rohan Sharma",
    time: "2h ago",
    type: "payment",
  },
  {
    id: "act_005",
    actor: "Prof. Arjun Nair",
    action: "marked attendance",
    target: "AI-N1 • 32 students",
    time: "4h ago",
    type: "attendance",
  },
];

export const exams = [
  {
    id: "exm_001",
    title: "Advanced Algorithms Midterm",
    course: "Advanced Distributed Systems",
    batch: "DS-M1",
    type: "MCQ",
    questions: 40,
    duration: "90 min",
    totalMarks: 100,
    scheduledFor: "Jun 20, 2024 • 10:00 AM",
    status: "Scheduled",
    attempts: 31,
  },
  {
    id: "exm_002",
    title: "Neural Networks Quiz 2",
    course: "Foundations of Neural Networks",
    batch: "AI-N1",
    type: "MCQ",
    questions: 15,
    duration: "30 min",
    totalMarks: 30,
    scheduledFor: "Jun 22, 2024 • 7:30 PM",
    status: "Draft",
    attempts: 0,
  },
  {
    id: "exm_003",
    title: "D3 Hands-On Assessment",
    course: "Data Visualization with D3",
    batch: "DS-E2",
    type: "Subjective",
    questions: 5,
    duration: "120 min",
    totalMarks: 50,
    scheduledFor: "Jun 18, 2024 • 6:00 PM",
    status: "Published",
    attempts: 12,
  },
];

export const assignments = [
  {
    id: "asg_001",
    title: "Distributed Key-Value Store Implementation",
    course: "Advanced Distributed Systems",
    batch: "DS-M1",
    due: "Jun 18, 2024 • 11:59 PM",
    submissions: 12,
    totalStudents: 28,
    status: "Active",
  },
  {
    id: "asg_002",
    title: "Backpropagation from Scratch",
    course: "Foundations of Neural Networks",
    batch: "AI-N1",
    due: "Jun 21, 2024 • 11:59 PM",
    submissions: 5,
    totalStudents: 32,
    status: "Active",
  },
  {
    id: "asg_003",
    title: "Design System Component Audit",
    course: "Mastering the Modern Toolchain",
    batch: "WEB-W1",
    due: "Jun 12, 2024 • 11:59 PM",
    submissions: 40,
    totalStudents: 40,
    status: "Grading",
  },
];

export const examQuestions = [
  {
    id: "q1",
    text: "Which of the following best describes the CAP theorem?",
    options: [
      "A distributed system can only guarantee two of three properties simultaneously",
      "Distributed systems require all three guarantees at all times",
      "Consistency is always achievable under network partitions",
      "Partition tolerance is optional for modern systems",
    ],
    correct: 0,
  },
  {
    id: "q2",
    text: "In Raft, what is the role of the leader election timeout?",
    options: [
      "It triggers a new election when a follower loses contact with the leader",
      "It schedules periodic log compaction",
      "It limits the number of write requests per second",
      "It determines the size of the replicated log",
    ],
    correct: 0,
  },
  {
    id: "q3",
    text: "What does 'eventual consistency' guarantee?",
    options: [
      "Replicas converge to the same value after updates cease",
      "Reads always return the most recent write",
      "All nodes update atomically",
      "The system can never experience a partition",
    ],
    correct: 0,
  },
];

export const attendanceData = {
  weekly: [
    { day: "MON", present: 92 },
    { day: "TUE", present: 95 },
    { day: "WED", present: 88 },
    { day: "THU", present: 96 },
    { day: "FRI", present: 91 },
    { day: "SAT", present: 78 },
    { day: "SUN", present: 0 },
  ],
  byBatch: [
    { batch: "DS-M1", rate: 94 },
    { batch: "AI-N1", rate: 89 },
    { batch: "WEB-W1", rate: 97 },
    { batch: "DS-E2", rate: 91 },
  ],
};

export const institutes = [
  {
    id: "ins_001",
    name: "Sunrise Academy",
    initials: "SA",
    domain: "sunriseacademy.in",
    owner: "Aarav Mehta",
    plan: "Enterprise",
    students: 1240,
    courses: 38,
    mrr: 12400,
    status: "Active",
    joined: "Jan 2024",
  },
  {
    id: "ins_002",
    name: "Crescent Coaching Centre",
    initials: "CC",
    domain: "crescentcoaching.in",
    owner: "Riya Kapoor",
    plan: "Pro",
    students: 860,
    courses: 24,
    mrr: 8600,
    status: "Active",
    joined: "Mar 2024",
  },
  {
    id: "ins_003",
    name: "Guru Academy",
    initials: "GA",
    domain: "guruacademy.in",
    owner: "Vikram Singh",
    plan: "Basic",
    students: 410,
    courses: 12,
    mrr: 4100,
    status: "Active",
    joined: "May 2024",
  },
  {
    id: "ins_004",
    name: "Iqra Learning Hub",
    initials: "IL",
    domain: "iqralearning.in",
    owner: "Sara Ahmed",
    plan: "Pro",
    students: 720,
    courses: 19,
    mrr: 7200,
    status: "Suspended",
    joined: "Feb 2024",
  },
  {
    id: "ins_005",
    name: "Sunrise Prep Academy",
    initials: "SP",
    domain: "sunriseprep.in",
    owner: "Mohammed Farhan",
    plan: "Enterprise",
    students: 2100,
    courses: 52,
    mrr: 21000,
    status: "Active",
    joined: "Nov 2023",
  },
];

export const examResults = [
  {
    id: "res_001",
    student: "Ayesha Khan",
    course: "Advanced Distributed Systems",
    score: 87,
    max: 100,
    percentage: 87,
  },
  {
    id: "res_002",
    student: "Rohan Sharma",
    course: "Advanced Distributed Systems",
    score: 72,
    max: 100,
    percentage: 72,
  },
  {
    id: "res_003",
    student: "Priya Patel",
    course: "Foundations of Neural Networks",
    score: 94,
    max: 100,
    percentage: 94,
  },
  {
    id: "res_004",
    student: "Mohammed Imran",
    course: "Foundations of Neural Networks",
    score: 58,
    max: 100,
    percentage: 58,
  },
  {
    id: "res_005",
    student: "Aisha Siddiqui",
    course: "Data Visualization with D3",
    score: 45,
    max: 50,
    percentage: 90,
  },
  {
    id: "res_006",
    student: "Rahul Verma",
    course: "Data Visualization with D3",
    score: 31,
    max: 50,
    percentage: 62,
  },
];
